import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

# Debe ser la PRIMERA llamada de Streamlit
st.set_page_config(page_title="Scouting LaLiga", layout="wide")

# (opcional si ya est√° en config.toml; no molesta si queda duplicado)
st.set_option("server.fileWatcherType", "none")
