import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

st.set_option("server.fileWatcherType", "none")  # ğŸ‘ˆ AÃ‘ADE ESTA LÃNEA
st.set_page_config(page_title="Scouting LaLiga", layout="wide")
